### ISSUE TITLE
Pickup Item Bug

### ISSUE THREAD

**Issue by MPNull** [chadalen/astraeus#28]
If I drop Rune Axe on the ground I can pick it up, but if I drop a Bronze Axe (on) it I cannot pickup Rune Axe.

So dropping a Bronze Axe and Rune Axe makes Rune Axe unlootable.

**Comment by IanWONeill** [comment]
Add this to the bottom of DropItemPacket.java

items.add(item);

**Comment by IanWONeill** [comment]
On a fresh copy of astreaus if you drop an item, it wont pickup again. Though if you add the items.add(item) it works - however if you drop an item on another that you dropped it wont pickup the first item. I havent looked much further into it than that.

**Comment by chadalen** [comment]
Fixed bbc8f6f9a2c82c4f65836ad26da99cf65949e684
