### ISSUE TITLE
A way to grab data.

### ISSUE THREAD

**Issue by IanWONeill** [chadalen/astraeus#34]
Do you have any good ideas for how I could dump data from data repos for 2007/OSRS? I know there is an api for RuneScape 3 which people take advantage of for Item and Npc information aswell as GE data, though the besiary - Im hoping that the NPC Id's are the same through 474 against RS3 so that i can just dump the ones for upto 474. as you can see here for Id=0:
http://services.runescape.com/m=itemdb_rs/bestiary/bestiary/beastData.json?beastid=0
Which gives:
{"size":1,"members":false,"animations":{},"name":"Hans","xp":"0.2","description":"Servant of the Duke of Lumbridge.","areas":["RuneScape Surface"],"id":0,"aggressive":false,"poisonous":false,"attackable":true}

Though according to the NPCDefinition in Astraeus the maximum amount 317 had was 2633
and this gives no output atall. Though 2634 gives:
{"size":1,"members":false,"animations":{},"name":"Miss Schism","xp":"0.2","description":"A busy-body who loves a bit of gossip.","areas":["RuneScape Surface","Draynor"],"id":2634,"aggressive":false,"poisonous":false,"attackable":true}

I attempted to try a library called JSOUP to try and parse the 2007runescape.wikia.com items and npc databases but had no success, I couldn't get my head arround it. If i used for example on an item page on https://try.jsoup.org/ and used the CSS query td (where things like bonuses are held) it would also throw out the release date of the item and other unnessicary data, and unless I had a "_", whitepaced Item list dumped from the cache i was using I wouldnt be able to open the page with a parser, then I'd have to sort of remove every nth line of the file to remove the junk...

Haha - anyway do you have any good ways of dumping or have dumps you can share?

**Comment by chadalen** [comment]
Use the version of OpenRS modified to work with OSRS. 
[OpenRS](https://github.com/kfricilone/OpenRS)

You can get a lot of information from the cache, the only information you're not able to get is stats. Which you have to parse from the wiki site.

**Comment by chadalen** [comment]
Going to close this issue since it's not an actual issue more general questions.

**Comment by IanWONeill** [comment]
Appreciate the info thanks.
