### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by TRMayhem** [chadalen/astraeus#41]
I'm having issues with logging into the server. My client works fine with other other frameworks. So far, I've found that the channel is closed due to an event state being equal to "IdleState.READER_IDLE". Not sure if I've set up the framework in my ide incorrectly, or if the server is incompatible with the client.

**Comment by chadalen** [comment]
Sounds like you need to remove this from the client, and also in the server.

https://github.com/chadalen/astraeus-client/blob/master/src/main/java/com/astraeus/Client.java#L7709

Let me know if this fixes the issue, I'll remove this and make the server and client follow the standard 317 login format.

**Comment by chadalen** [comment]
@TRMayhem The issue isn't RSA it's UUID.

**Comment by TRMayhem** [comment]
It's still not working, so far all I can find out is that the channel is inactive, but that doesn't really tell me any good reason why it's not working. I've tested another source to see if my client connects fine, and my client does to it, but not Astraeus. Here's the only reported message (x3):

Mar 31, 2017 12:31:53 AM astraeus.game.model.entity.mob.player.Player onDeregister
INFO: [DEREGISTERED]: [host= censored]
